services:
  api:
    build:
      context: ./random-number-api
    ports:
      - "3001:3000"
    networks:
      - app-network

  client:
    build:
      context: ./random-number-client
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
