# Usar una imagen base de Node.js
FROM node:18

# Crear un directorio para la aplicación
WORKDIR /usr/src/app

# Copiar el package.json y el package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Compilar la aplicación
RUN npm run build

# Exponer el puerto en el que la API escucha
EXPOSE 3000

# Ejecutar la aplicación
CMD ["npm", "run", "start:prod"]
